// Predefined quiz flows para comunicação visual
export const VISUAL_COMMUNICATION_QUIZ_FLOWS = {
    OUTDOOR: {
        id: "outdoor-materials",
        name: "Materiais para Comunicação Externa",
        description: "Identifique o material ideal para aplicações externas",
        category: "outdoor",
        estimatedTime: 3,
        questions: [
            {
                id: "environment",
                type: "single-choice",
                title: "Onde será aplicado o material?",
                description: "Ambiente de aplicação determina resistência necessária",
                options: [
                    {
                        id: "facade",
                        label: "Fachada/Empena",
                        value: "facade",
                        description: "Aplicação em paredes externas de edifícios",
                        icon: "🏢",
                        score: 30,
                    },
                    {
                        id: "vehicle",
                        label: "Veículo",
                        value: "vehicle",
                        description: "Adesivação de carros, caminhões, etc.",
                        icon: "🚗",
                        score: 25,
                    },
                    {
                        id: "totem",
                        label: "Totem/Placa",
                        value: "totem",
                        description: "Placas de identificação e sinalização",
                        icon: "🪧",
                        score: 20,
                    },
                    {
                        id: "banner",
                        label: "Banner/Faixa",
                        value: "banner",
                        description: "Materiais flexíveis para eventos",
                        icon: "🎪",
                        score: 15,
                    },
                ],
            },
            {
                id: "durability",
                type: "single-choice",
                title: "Por quanto tempo o material ficará exposto?",
                description: "Durabilidade necessária afeta o tipo de material",
                options: [
                    {
                        id: "temporary",
                        label: "Até 6 meses",
                        value: "temporary",
                        description: "Aplicações temporárias e promocionais",
                        score: 10,
                    },
                    {
                        id: "medium",
                        label: "6 meses a 3 anos",
                        value: "medium",
                        description: "Aplicações de médio prazo",
                        score: 20,
                    },
                    {
                        id: "permanent",
                        label: "Mais de 3 anos",
                        value: "permanent",
                        description: "Aplicações permanentes",
                        score: 30,
                    },
                ],
            },
            {
                id: "surface",
                type: "single-choice",
                title: "Qual o tipo de superfície?",
                description: "Tipo de superfície determina adesividade necessária",
                options: [
                    {
                        id: "smooth",
                        label: "Lisa (vidro, metal)",
                        value: "smooth",
                        description: "Superfícies lisas e regulares",
                        score: 25,
                    },
                    {
                        id: "textured",
                        label: "Texturizada (parede, madeira)",
                        value: "textured",
                        description: "Superfícies com textura ou irregulares",
                        score: 20,
                    },
                    {
                        id: "curved",
                        label: "Curvada (veículos, cilindros)",
                        value: "curved",
                        description: "Superfícies com curvas e relevos",
                        score: 30,
                    },
                ],
            },
        ],
    },
    INDOOR: {
        id: "indoor-materials",
        name: "Materiais para Comunicação Interna",
        description: "Identifique o material ideal para aplicações internas",
        category: "indoor",
        estimatedTime: 2,
        questions: [
            {
                id: "purpose",
                type: "single-choice",
                title: "Qual a finalidade do material?",
                description: "Uso específico determina características necessárias",
                options: [
                    {
                        id: "signage",
                        label: "Sinalização",
                        value: "signage",
                        description: "Placas identificadoras e direcionais",
                        icon: "➡️",
                        score: 25,
                    },
                    {
                        id: "decoration",
                        label: "Decoração",
                        value: "decoration",
                        description: "Ambientação e decoração de espaços",
                        icon: "🎨",
                        score: 20,
                    },
                    {
                        id: "display",
                        label: "Display/Expositor",
                        value: "display",
                        description: "Materiais para stands e expositores",
                        icon: "📱",
                        score: 30,
                    },
                    {
                        id: "branding",
                        label: "Branding Corporativo",
                        value: "branding",
                        description: "Identidade visual corporativa",
                        icon: "🏢",
                        score: 25,
                    },
                ],
            },
            {
                id: "quality",
                type: "single-choice",
                title: "Qual nível de qualidade desejado?",
                description: "Qualidade afeta aparência e durabilidade",
                options: [
                    {
                        id: "economy",
                        label: "Econômico",
                        value: "economy",
                        description: "Custo-benefício para uso temporário",
                        score: 10,
                    },
                    {
                        id: "standard",
                        label: "Padrão",
                        value: "standard",
                        description: "Qualidade intermediária para uso geral",
                        score: 20,
                    },
                    {
                        id: "premium",
                        label: "Premium",
                        value: "premium",
                        description: "Alta qualidade para aplicações nobres",
                        score: 30,
                    },
                ],
            },
        ],
    },
    PRINTING: {
        id: "printing-materials",
        name: "Materiais para Impressão",
        description: "Identifique o substrato ideal para impressão",
        category: "printing",
        estimatedTime: 4,
        questions: [
            {
                id: "printType",
                type: "single-choice",
                title: "Qual tipo de impressão será utilizada?",
                description: "Tecnologia de impressão determina compatibilidade",
                options: [
                    {
                        id: "digital",
                        label: "Impressão Digital",
                        value: "digital",
                        description: "Jato de tinta eco-solvente ou UV",
                        score: 25,
                    },
                    {
                        id: "offset",
                        label: "Offset",
                        value: "offset",
                        description: "Impressão offset para grandes tiragens",
                        score: 20,
                    },
                    {
                        id: "screen",
                        label: "Serigrafia",
                        value: "screen",
                        description: "Serigrafia para cores chapadas",
                        score: 15,
                    },
                    {
                        id: "sublimation",
                        label: "Sublimação",
                        value: "sublimation",
                        description: "Sublimação para tecidos",
                        score: 20,
                    },
                ],
            },
            {
                id: "finish",
                type: "single-choice",
                title: "Qual acabamento desejado?",
                description: "Acabamento afeta aparência final",
                options: [
                    {
                        id: "matte",
                        label: "Fosco",
                        value: "matte",
                        description: "Acabamento fosco sem reflexo",
                        score: 15,
                    },
                    {
                        id: "gloss",
                        label: "Brilhante",
                        value: "gloss",
                        description: "Acabamento brilhante com reflexo",
                        score: 20,
                    },
                    {
                        id: "satin",
                        label: "Semi-brilho",
                        value: "satin",
                        description: "Acabamento intermediário",
                        score: 25,
                    },
                ],
            },
            {
                id: "size",
                type: "slider",
                title: "Qual o tamanho aproximado (m²)?",
                description: "Tamanho influencia escolha do material",
                validation: {
                    min: 0.1,
                    max: 100,
                    required: true,
                },
            },
        ],
    },
};
